services:
  mineralforge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mineralforge_edge_demo
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app
    command: python main.py --zone "Stope 3" --stress 2.8
