"""
JR MineralForge – Explanation, Interpretability & Reporting Agent
==================================================================
Produces branded reports, SHAP explanation diagrams, ranked target summaries,
and human-readable geological interpretations for Team JR outputs.
"""

from __future__ import annotations

import json
import datetime
from pathlib import Path
from typing import Optional, List, Dict, Any, Tuple

import numpy as np
import pandas as pd

# Optional matplotlib for SHAP plots
try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    HAS_MPL = True
except ImportError:
    HAS_MPL = False

try:
    import shap
    HAS_SHAP = True
except ImportError:
    HAS_SHAP = False

from langchain.tools import tool

from config.settings import (
    REPORTS_DIR, BRAND_NAME, TEAM_NAME, BRAND_HEADER, BRAND_FOOTER,
    WINNERS_CONTEXT, MOUNT_WOODS_BBOX, ML_CONFIG,
)
from utils.logging_utils import get_logger

log = get_logger(__name__)


# ─────────────────────────────────────────────────────────────────
# Report Generation
# ─────────────────────────────────────────────────────────────────

REPORT_TEMPLATE_HTML = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{brand_name} – Executive Drill Target Brief</title>
    <style>
        body {{ font-family: 'Inter', 'Segoe UI', sans-serif; background-color: #0d1117; color: #e6edf3; padding: 40px; margin: 0 auto; max-width: 900px; }}
        h1 {{ color: #FFD700; border-bottom: 2px solid #FFD700; padding-bottom: 10px; }}
        h2 {{ color: #4a9eff; margin-top: 30px; }}
        .header-box {{ background: #1a2035; padding: 20px; border-left: 4px solid #FFD700; border-radius: 4px; margin-bottom: 30px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 15px; background: #1a2035; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #2d3748; }}
        th {{ background-color: #2d3748; color: #FFD700; font-weight: bold; }}
        .disclaimer {{ font-size: 0.8em; color: #8b949e; margin-top: 50px; text-align: justify; padding-top: 20px; border-top: 1px dashed #2d3748; }}
    </style>
</head>
<body>
    <h1>{brand_name} | Drill or Drop Decision Brief</h1>
    <div class="header-box">
        <p><strong>Generated:</strong> {timestamp}</p>
        <p><strong>Target Tenement Constraint:</strong> {aoi}</p>
        <p><strong>Pipeline Strategy:</strong> Unsupervised ML (Isolation Forest) with SHAP Interrogation</p>
    </div>

    <h2>Executive Summary</h2>
    <p>{executive_summary}</p>

    <h2>Ranked Geological Targets</h2>
    {targets_html}

    <h2>Primary Machine Learning Drivers (SHAP)</h2>
    <p>Targets were generated by identifying multivariate anomalies against the background structural domain. The Primary Drivers listed indicate the top geospatial anomaly dictating target ranking.</p>

    <h2>Data Layer Lineage</h2>
    <ul>
        <li><strong>SARIG Vector Subsystem:</strong> Dynamic clipping from official <i>services.sarig.sa.gov.au/vector</i> WFS nodes.</li>
        <li><strong>Geoscience Australia Grids:</strong> National Bouguer Gravity, Radiometrics (K/eU/eTh), and TMI Magnetics constraints.</li>
    </ul>

    <div class="disclaimer">
        <strong>CONFIDENTIAL - COMMERCIAL IN CONFIDENCE</strong><br>
        This algorithmic targeting sequence relies on open Government Data intersected with ML techniques. Probable anomaly zones must be independently verified by Senior Geoscientists via localized soil geochemistry and infill ground magnetics prior to any Diamond Drilling (DD) or RC commitment.
    </div>
</body>
</html>
"""

def generate_executive_html_brief(
    targets_df: Optional[pd.DataFrame] = None,
    output_path: Optional[Path] = None,
) -> str:
    """Generate a standalone Commercial HTML decision brief for Mining Executives."""
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S AEST")

    n_targets = len(targets_df) if targets_df is not None else 0
    exec_summary = (
        f"Algorithm successfully parsed the <b>{MOUNT_WOODS_BBOX.name}</b> boundary vector. "
        f"The Prospectivity Mapping Engine isolated exactly <b>{n_targets}</b> critical anomalies within the geometry. "
        f"Each drill target has been mapped, cross-validated via robust bounding boxes, and "
        f"explained via SHAP attribution to establish pipeline transparency."
    )

    if targets_df is not None and not targets_df.empty:
        df_display = targets_df.copy()
        if "confidence_score" in df_display.columns:
            df_display["confidence_score"] = df_display["confidence_score"].apply(lambda x: f"{x:.1f}%")
        if "lat" in df_display.columns and "lon" in df_display.columns:
            df_display["Easting"] = df_display["lon"].round(2)
            df_display["Northing"] = df_display["lat"].round(2)
            
        display_cols = [c for c in ["target_label", "confidence_category", "confidence_score", "primary_driver", "Easting", "Northing"] if c in df_display.columns]
        targets_html = df_display[display_cols].head(15).to_html(index=False, classes="table table-striped")
    else:
        targets_html = "<p>No isolated targets matched the minimum confidence threshold.</p>"

    report = REPORT_TEMPLATE_HTML.format(
        brand_name=BRAND_NAME,
        timestamp=timestamp,
        aoi=MOUNT_WOODS_BBOX.name,
        executive_summary=exec_summary,
        targets_html=targets_html
    )

    if output_path is None:
        output_path = REPORTS_DIR / "jr_drill_or_drop_brief.html"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report, encoding="utf-8")
    log.info(f"Commercial Brief HTML saved → {output_path}")
    return report


# ─────────────────────────────────────────────────────────────────
# SHAP Summary Plot
# ─────────────────────────────────────────────────────────────────

def plot_shap_summary(
    shap_values: np.ndarray,
    feature_names: List[str],
    output_path: Optional[Path] = None,
) -> Optional[Path]:
    """Generate a SHAP beeswarm summary plot for Team JR report branding."""
    if not HAS_SHAP or not HAS_MPL:
        log.warning("SHAP or matplotlib not available — skipping SHAP plot")
        return None

    fig, ax = plt.subplots(figsize=(10, 7))
    ax.set_facecolor("#0a0a1a")
    fig.patch.set_facecolor("#0a0a1a")

    mean_abs = np.abs(shap_values).mean(axis=0)
    sorted_idx = np.argsort(mean_abs)[::-1][:20]  # top 20
    names = [feature_names[i] for i in sorted_idx]
    vals = mean_abs[sorted_idx]

    colours = plt.cm.RdYlGn(np.linspace(0.2, 0.9, len(names)))
    ax.barh(range(len(names)), vals[::-1], color=colours[::-1])
    ax.set_yticks(range(len(names)))
    ax.set_yticklabels(names[::-1], color="white", fontsize=10)
    ax.set_xlabel("Mean |SHAP Value|", color="white")
    ax.set_title(
        f"{BRAND_NAME} – Feature Importance (SHAP)\n{BRAND_HEADER}",
        color="#FFD700", fontsize=11, pad=15,
    )
    ax.tick_params(colors="white")
    for spine in ax.spines.values():
        spine.set_edgecolor("#444")
    ax.text(
        0.01, -0.08, BRAND_FOOTER,
        transform=ax.transAxes, fontsize=7, color="#888",
        ha="left",
    )
    plt.tight_layout()

    if output_path is None:
        output_path = REPORTS_DIR / "shap_importance.png"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close()
    log.info(f"SHAP plot saved → {output_path}")
    return output_path


def plot_target_confidence(
    targets_df: pd.DataFrame,
    output_path: Optional[Path] = None,
) -> Optional[Path]:
    """Bar chart of top-ranked target confidence scores."""
    if not HAS_MPL or targets_df is None or len(targets_df) == 0:
        return None

    df = targets_df.head(20).copy()
    if "confidence_score" not in df.columns:
        return None

    fig, ax = plt.subplots(figsize=(12, 6))
    ax.set_facecolor("#0d1117")
    fig.patch.set_facecolor("#0d1117")

    labels = df.get("target_label", pd.Series(range(len(df)))).values
    scores = df["confidence_score"].values
    uncertainties = df.get("uncertainty", pd.Series(np.zeros(len(df)))).values * 100

    colours = ["#ff4444" if s > 85 else "#ff9900" if s > 70 else "#44cc44" for s in scores]
    bars = ax.barh(range(len(labels)), scores, color=colours, alpha=0.85)
    if uncertainties.sum() > 0:
        ax.barh(
            range(len(labels)), uncertainties, left=scores,
            color="#888888", alpha=0.4, label="Uncertainty (±)"
        )

    ax.set_yticks(range(len(labels)))
    ax.set_yticklabels(labels, color="white", fontsize=9)
    ax.set_xlabel("Confidence Score (%)", color="white")
    ax.set_title(
        f"{BRAND_NAME} – Ranked Drill Targets\n{BRAND_HEADER}",
        color="#FFD700", fontsize=11, pad=10,
    )
    ax.set_xlim(0, 110)
    ax.axvline(x=70, color="#ff9900", linestyle="--", alpha=0.5, label="High threshold")
    ax.axvline(x=85, color="#ff4444", linestyle="--", alpha=0.5, label="Very High threshold")
    ax.tick_params(colors="white")
    ax.legend(facecolor="#1a1a2e", labelcolor="white", fontsize=8)
    for spine in ax.spines.values():
        spine.set_edgecolor("#333")
    ax.text(
        0.01, -0.08, BRAND_FOOTER,
        transform=ax.transAxes, fontsize=7, color="#888", ha="left"
    )
    plt.tight_layout()

    if output_path is None:
        output_path = REPORTS_DIR / "target_confidence.png"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close()
    log.info(f"Target confidence chart saved → {output_path}")
    return output_path


# ─────────────────────────────────────────────────────────────────
# LangChain Tools
# ─────────────────────────────────────────────────────────────────

@tool
def generate_full_report(targets_json: str = "{}") -> str:
    """
    Generate a complete JR MineralForge HTML prospectivity brief.
    targets_json: JSON string with target data (optional; uses last pipeline run data).
    Returns the path to the HTML brief and a short preview.
    """
    try:
        targets_data = json.loads(targets_json) if targets_json.strip() not in ("{}", "") else {}
        targets_df = pd.DataFrame(targets_data) if targets_data else None
    except Exception:
        targets_df = None

    report = generate_executive_html_brief(targets_df=targets_df)
    return f"HTML Brief generated successfully!\n\nPreview (first 1000 chars):\n{report[:1000]}…"


@tool
def explain_target(target_label: str, features_json: str = "{}") -> str:
    """
    Provide a geological explanation for a specific ranked drill target.
    target_label: e.g. 'JR-T001'
    features_json: JSON dict of feature values at the target location (optional).
    """
    try:
        features = json.loads(features_json) if features_json.strip() not in ("{}", "") else {}
    except Exception:
        features = {}

    lines = [
        f"[{BRAND_NAME}] Geological Explanation for {target_label}",
        "=" * 55,
    ]

    # Build feature narrative
    if features:
        lines.append("\nFeature Values at Target Location:")
        for feat, val in features.items():
            lines.append(f"  {feat}: {val}")
        lines.append("")

        # Geological interpretation
        if "tmi" in features and features.get("tmi", 0) < -100:
            lines.append("📍 Strong negative TMI anomaly → possible magnetite destruction / hematite breccia (IOCG proxy)")
        if "gravity" in features and features.get("gravity", 0) < -10:
            lines.append("📍 Gravity low → low-density breccia body or granitic intrusion at depth (IOCG proxy)")
        if "k_pct" in features and features.get("k_pct", 0) > 3.0:
            lines.append("📍 Elevated K% → potassic alteration halo (strong IOCG proxy)")
        if "k_eth_ratio" in features and features.get("k_eth_ratio", 0) > 0.5:
            lines.append("📍 High K/eTh ratio → confirms K enrichment is alteration-related, not lithological")
    else:
        lines.append("No feature data provided. Query the prospectivity pipeline for feature extraction.")

    lines.append(f"\n{BRAND_FOOTER}")
    return "\n".join(lines)
